"""add_meal_date_and_meal_type_to_orders

Revision ID: 52a06862ef2d
Revises: a1b2c3d4e5f6
Create Date: 2026-05-15 15:04:49.063793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a06862ef2d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('meal_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('meal_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'meal_type')
    op.drop_column('orders', 'meal_date')
    # ### end Alembic commands ###
