"""Phase 6: Add system_logs indexes

Revision ID: 8a258d50ee87
Revises: f94f55868e87
Create Date: 2026-05-08 23:07:08.631660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a258d50ee87'
down_revision: Union[str, Sequence[str], None] = 'f94f55868e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_system_logs_action', 'system_logs', ['action'], unique=False)
    op.create_index('ix_system_logs_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('ix_system_logs_user_id', 'system_logs', ['user_id'], unique=False)
    # SQLite 批模式：以表重建方式创建唯一约束（原始 ALTER 在 SQLite 上不支持）
    with op.batch_alter_table('taste_preferences', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_ingredient_pref', ['user_id', 'ingredient_id', 'preference_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 批模式：以表重建方式删除唯一约束
    with op.batch_alter_table('taste_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_ingredient_pref', type_='unique')
    op.drop_index('ix_system_logs_user_id', table_name='system_logs')
    op.drop_index('ix_system_logs_created_at', table_name='system_logs')
    op.drop_index('ix_system_logs_action', table_name='system_logs')
    # ### end Alembic commands ###
