"""Add model relationships: Order.user, Order.chef, DishIngredient.ingredient, DishCategory.category, Favorite.dish

Revision ID: ce21c5492d5a
Revises: 782ece94f451
Create Date: 2026-05-08 17:55:51.898520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce21c5492d5a'
down_revision: Union[str, Sequence[str], None] = '782ece94f451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
