"""Phase 5: Add favorites, taste_preferences constraints, and chef_schedules table

Revision ID: f94f55868e87
Revises: ce21c5492d5a
Create Date: 2026-05-08 18:36:01.398279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94f55868e87'
down_revision: Union[str, Sequence[str], None] = 'ce21c5492d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chef_id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chef_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chef_id', 'schedule_date', 'meal_type', name='uq_chef_date_meal')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dish_id', name='uq_user_dish_favorite')
    )
    
    # SQLite 需要使用 batch 模式来添加约束
    with op.batch_alter_table('taste_preferences', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_ingredient_pref', ['user_id', 'ingredient_id', 'preference_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taste_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_ingredient_pref', type_='unique')
    op.drop_table('favorites')
    op.drop_table('chef_schedules')
    # ### end Alembic commands ###